### ISSUE TITLE
Add ability to subscribe/broadcast to other streams over websockets not directly related to models

### ISSUE THREAD

**Issue by davish** [hotwire-django/turbo-django#14]

**Comment by C4ptainCrunch** [comment]
I'm adding a bit of context, since this comes from a Slack discussion.

---

> One example of a non-model stream: let's say I want to use the django messages API, but without a redirect like a "toaster" popup sent from the server sometimes you might want a model, sure, but also I might want it sent from a signal, like when a friend logs into your app.
