### ISSUE TITLE
Move documentation to readthedocs.io

### ISSUE THREAD

**Issue by davish** [hotwire-django/turbo-django#15]
I'm partial to [mkdocs](https://github.com/mkdocs/mkdocs/) with its focus on markdown but, but am open to discussion on this!

**Comment by JulianFeinauer** [comment]
Personally I prefer markdown too but if somebody is able to set it up the "python way" (sphinx and remarkable or how its called) @danjac *twinkle, twinkle* I would prefer that, I think.

**Comment by C4ptainCrunch** [comment]
I've never used mkdocs but i do indeed prefer writing Markdown than RST. I guess we should do a vote here as it has big consequences (i'm already voting blank ^^)

If we go the RST+Shpinx i volunteer to do the setup with readthedocs, i'm quite used to it.

---
Other question (that we might not want to solve here or now): should we do something like hotwire.dev where there is a landing page linking to each project docs ? Should we also buy a .dev domain (i'm explicitly not writing the domain name here, don't want a 🤖 picking it up and buying the domain before us)

**Comment by C4ptainCrunch** [comment]
So it seems like @davish and @JulianFeinauer prefer Markdown but @danjac uses Sphinx in hotwire-django/django-turbo-response. Should we do a formal vote ? The one that implements it just chooses ?

**Comment by JulianFeinauer** [comment]
Documentation is now here in a first version: https://turbo-django.readthedocs.io/en/latest/
