### ISSUE TITLE
Custom turbo-channels-stream-source element can't be self closing

### ISSUE THREAD

**Issue by TeamTeaTime** [hotwire-django/turbo-django#41]
Hello! Thanks everyone for putting this library together. 

This isn't major, but I believe that you can't have self closing custom elements (https://developers.google.com/web/fundamentals/web-components/customelements#define) so turbo_stream_source.html should be:
`<turbo-channels-stream-source signed-channel-name="{{ channel_name }}"></turbo-channels-stream-source>`
Currently the custom element subsumes the other elements below it, which hasn't broken anything so far for me, but I don't think it's the intended behavior.

**Comment by scuml** [comment]
Good find - fixed in #44.
