### ISSUE TITLE
render() requries context (Components require documentation)

### ISSUE THREAD

**Issue by nerdoc** [hotwire-django/turbo-django#55]
In #53 (I didn't find another documentation of Components) you write at the end: `cart_component.render()` - but the render function has a mandatory `context` parameter.

So in my tests I could not get this to work...

Is there any documentation for Components (which are GREAT!)?

**Comment by scuml** [comment]
I reorganized the render() methods and fixed the issue with a required context parameter and republished version 0.4.2 with the fixes.  

Docs are up on https://turbo-django.readthedocs.io/en/latest/topics/components.html
Feel free to edit to add clarity.

The idea is that render() will, by default, pull context from the class's `get_context()` method.  So, in this case, a call to `render()` with no parameters will auto-calculate the count.

```
    def get_context(self):
        return {"count": user.cart.items_in_cart}
```

If you are just testing and don't want to mock a user with a Cart model, replace `user.cart.items_in_cart` with `99` or some other number.   

Then in a shell, call
```python
cart_count_component.render(count=33)  # these will override the context
cart_count_component.render({'count': 44})
cart_count_component.render(count=0)
cart_count_component.render()  # this will use the value in get_context()
```
