### ISSUE TITLE
component subscription calls without "user"

### ISSUE THREAD

**Issue by nerdoc** [hotwire-django/turbo-django#58]
The AlertBroadcastComponent example works well, but when I change to the UserBroadcastComponent, the example starts as normal, the webpage renders, but after a few seconds, I get an error:
```
User `None` does not have permission to access stream 'prescriptions:AlertBroadcastComponent'.
```

I tried to dig into that, but could not find the culprit... But I think this is a bug.

**Comment by scuml** [comment]
That is to be expected.  You have an anonymous user and the log is letting you know the permissions check failed. 

Add
```python
    def user_passes_test(self, user):
        return True
```
and the error will go away.

**Comment by nerdoc** [comment]
Hm, but I am logged in as user in this case...

**Comment by scuml** [comment]
OK - I'll check it out.

**Comment by nerdoc** [comment]
That may be a really nasty bug. AlertBroadcastComponent and UserAlertBroadcastComponent don't differ much. But, when `user_passes_test(user)` is called by `receive_json` the first time, `user` is None.

Sure, if I add a `def user_passes_test(self, user): return True`, it works - but then again the alert is shown to any user.

IMHO, there should anyway be some other code in `UserAlertBroadcastComponent`:
```python
def user_passes_test(self, user):
    return user.is_authenticated and user==self.user
```
because ATM it does **nothing** with `self.user` - which seems cumbersome to me. But it doesn't work in the first place because of `receive_json` calling `user_passes_test(user)` IMHO **before** at a time before the user is assigned to the request...?

**Comment by nerdoc** [comment]
Ok, a few infos more.
UserBroadcastComponent sets the given user from the client's subscriptiond as self.user. 

Have a look at `turbo/consumers.py`, line 30ff, in `receive_json()`:

```python
    def receive_json(self, content, **kwargs):
        try:
            stream_name, args, kwargs = signer.unsign_object(content["signed_channel_name"])
            # now args = user.pk ! correct
    # ...
        if Stream:
            stream = Stream(*args, **kwargs)  # this is correctly instanciated with user.pk as args[0]

    # but here comes the problem IMHO
    self.subscribe_to_stream(message_type, stream, self.scope.get("user"))
```
`self.scope.get("user")` is `None`. 

So IMHO here lies the culprit. I don't know why, @scuml  maybe you have a deeper insight here.

**Comment by nerdoc** [comment]
is it possible that Channels needs a different form of authentication than Django WSGI? according to the [channels scopedoc](https://channels.readthedocs.io/en/latest/topics/consumers.html#scope) and [Authentication](https://channels.readthedocs.io/en/latest/topics/authentication.html), Channels' AuthMiddleware is needed...
If so, this definitely must be included in the TurboDjango docs / tutorial...

**Comment by nerdoc** [comment]
Without knowing Channels' internals, the following fixes the issue: wrap `TurboStreamsConsumer` with `AuthMiddlewareStack` in the [turbo installation docs](https://turbo-django.readthedocs.io/en/latest/installation.html):
```python
from channels.auth import AuthMiddlewareStack

# ...

application = ProtocolTypeRouter({
  "http": get_asgi_application(),
  "websocket": TurboStreamsConsumer.as_asgi()
})
```
