### ISSUE TITLE
user_passes_test signature?

### ISSUE THREAD

**Issue by nerdoc** [hotwire-django/turbo-django#59]
in the [ModelStream example](https://turbo-django.readthedocs.io/en/latest/topics/model_stream.html) at the end, there is the `user_passes_test` method:

```python
def user_passes_test(self, user, object_id):
    return True
```
This signature does not match the parent's signature:
```python
def user_passes_test(self, user):
    pass
```

Could it be that you forgot `,*args, **kwargs` in ModelStream? Or is the `object_id` obsolete?

**Comment by scuml** [comment]
`object_id` is no longer needed.  

Since all ModelStreams are related to a specific model instance, one can use:
```
        def user_passes_test(self, user):
            if user.can_access_message(self.pk):
                return True
            return False
```

I've updated the documentation and example code.

Thanks for the extra eyes on this and astute observations.  Very much appreciated.
