### ISSUE TITLE
UUID as a primary key

### ISSUE THREAD

**Issue by meesix** [hotwire-django/turbo-django#61]
Hey, it might be something that can be easily solved, but my initial approach to turbo-django is stoped by "Object of type UUID is not JSON serializable" error.

**Error**:
site-packages/turbo/templates/turbo/turbo_stream_source.html, error at line 2
`<turbo-channels-stream-source signed-channel-name="**{{ stream.signed_stream_name }}**" args="{{ stream.get_init_args_json }}" kwargs="{{ stream.get_init_kwargs_json }}"></turbo-channels-stream-source>`

site-packages/django/core/signing.py, line 117, in dumps
`data = serializer().dumps(obj)`

**Model**:
`class MyModel(models.Model):`
  ` id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)`

**Comment by scuml** [comment]
Thanks for the helpful report.  I believe I've come up with a solution to this problem.  Released in turbo-django 0.4.3
